//
// Created by jbili on 19.03.2021.
//

#ifndef CLUSEK_RT_SERIALIZATIONMACROS_H
#define CLUSEK_RT_SERIALIZATIONMACROS_H

#include "CommonMacros.h"

GENERATOR_SKIP_THIS_FILE()

#define SERIALIZE_OBJECT(NAME)
#define SERIALIZE_FIELD(NAME, TYPE)

#endif //CLUSEK_RT_SERIALIZATIONMACROS_H
