//  _____  _____  _   _  _____ ______   ___   _____  _____ ______ 
// |  __ \|  ___|| \ | ||  ___|| ___ \ / _ \ |_   _||  ___||  _  \
// | |  \/| |__  |  \| || |__  | |_/ // /_\ \  | |  | |__  | | | |
// | | __ |  __| | . ` ||  __| |    / |  _  |  | |  |  __| | | | |
// | |_\ \| |___ | |\  || |___ | |\ \ | | | |  | |  | |___ | |/ /
//  \____/\____/ \_| \_/\____/ \_| \_|\_| |_/  \_/  \____/ |___/
//
// ---------------------------------------------------------------------------------------------------------------------
//
//                                                  Warning!
// Never modify this file by hand, because it's automatically generated by an external tool and will be overwritten.
//
// ---------------------------------------------------------------------------------------------------------------------

#ifndef {{ guardName }}
#define {{ guardName }}

#include <nlohmann/json.hpp>
#include <string>

{{ #serializableObjects }}
#include "{{ includeObjectPath }}"
{{ /serializableObjects }}

#define LOAD_PRIMITIVE_DATA_TO_FIELD(JSON, OBJECT, FIELD, TYPE) if (!JSON[#FIELD].is_null()) OBJECT.FIELD = JSON[#FIELD].get<TYPE>();

namespace {{ namespace }}
{
// DESERIALIZERS
{{ #serializableObjects }}
    void Deserialize(std::ifstream& fileStream, {{ objectName }}& object)
    {
        nlohmann::json json;
        fileStream >> json;
    }
{{ /serializableObjects }}

// SERIALIZERS
{{ #serializableObjects }}
{{ /serializableObjects }}
};

#endif //{{ guardName }}